platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
  - name: trial-psa
  - name: resource-version

outputs:
  - name: build-src

caches:
  - path: .gradle/
  - path: .m2/

run:
  path: trial-psa/ci/build.sh
