resource_types:
- name: artifactory
  type: docker-image
  source:
    repository: pivotalservices/artifactory-resource

resources:
- name: trial-psa
  type: git
  source:
    uri: https://github.com/MapleInSpring/trial-psa.git
    branch: master
    skip_ssl_verification: true

jobs:
- name: trial-round
  plan:
  - get: trial-psa
    trigger: true
  - task: build
    file: trial-psa/ci/build.yml
